spring:
  profiles:
    active: local
  application:
    name: gym-service-client
  mvc:
    servlet:
      path: /

server:
  port: 8886
  servlet:
    context-path: /
  error:
    path: /error
    whitelabel:
      enabled: false

gym:
  service:
    baseUrl: 'localhost:8585/api/training-session'
    searchSession: '/search'