spring:
  profiles:
    active: local
  application:
    name: gym-service-client

server:
  port: 8886

gym:
  service:
    baseUrl: 'localhost:8585/api/training-session'
    searchSession: '/search'